input_image_dir: ./data/inputs
output_dir: ./data/outputs
conf_threshold: 0.7
model_path: ../models/yolo-segmentation-weights.pt
left_labels: [I, II, III, aVL, aVR, aVF]
right_labels: [V1, V2, V3, V4, V5, V6]